name: Deploy admin-ui

run-name: "Deploy admin-ui ${{ inputs.env }} ${{ inputs.image_tag }}"

on:
  workflow_call:
    inputs:
      env:
        description: "Environment"
        required: true
        type: string
        default: ""
      image_tag:
        description: "Docker image tag (latest or the commit SHA)"
        required: false
        type: string
        default: "latest"
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        type: environment
        default: ""
      image_tag:
        description: "Docker image tag (latest or the commit SHA)"
        required: false
        type: string
        default: "latest"

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  IMAGE_NAME: "arxiv-admin-console/admin-console-ui"

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check version
        run: terraform --version

      - name: Format check
        run: terraform fmt -check -recursive terraform/admin-ui

  deploy:
    runs-on: ubuntu-latest
    needs: format-check
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set GCP bucket name
        run: echo "GCP_BUCKET=$(echo '${{ vars.ENV_VAR }}' | tr '[:upper:]' '[:lower:]')-admin-console-test" >> $GITHUB_ENV

      - name: Authenticate with target project workload identity
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/github-actions-provider
          service_account: github-actions-sa@${{ vars.PROJECT_NAME }}.iam.gserviceaccount.com
          project_id: ${{ vars.PROJECT_NAME }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check version
        run: terraform --version

      - name: Set environment variables
        run: |
          TERRAFORM_ARGS="-var-file=\"envs/${{ vars.ENV_VAR }}.tfvars\"
          #  -var=\"image_path=gcr.io/arxiv-development/${{env.IMAGE_NAME}}:${{inputs.image_tag}}\""

          echo "TERRAFORM_ARGS=$TERRAFORM_ARGS" >> $GITHUB_ENV
        working-directory: terraform/admin-ui

      - name: Initialize admin-ui remote backend
        run: terraform init -backend-config="bucket=${{ vars.TERRAFORM_BUCKET }}"
        working-directory: terraform/admin-ui

      - name: Apply
        run: terraform apply ${{ env.TERRAFORM_ARGS }} -auto-approve
        working-directory: terraform/admin-ui

      - name: Pull image
        working-directory: ui-arxiv-admin
        run: |
          docker pull gcr.io/arxiv-development/${{env.IMAGE_NAME}}:${{inputs.image_tag}}
          docker images -a

      - name: Create container
        working-directory: ui-arxiv-admin
        run: |
          docker create --name admin-console gcr.io/arxiv-development/${{env.IMAGE_NAME}}:${{inputs.image_tag}}
          docker ps -a

      # the Docker image must have the gcloud SDK or a client library to cp directly to the bucket ...

      - name: Copy app from container
        working-directory: ui-arxiv-admin
        run: |
          docker cp admin-console:/usr/share/nginx/html/admin-console admin-console
          find admin-console -type d -exec chmod 755 {} \; 2>/dev/null
          find admin-console -type f -exec chmod 644 {} \; 2>/dev/null
          echo "----"
          ls -asl
          echo "----"
          ls -aslR admin-console

      - name: Upload to GCP
        run: |
          gsutil rsync -r ./admin-console gs://${{ env.GCP_BUCKET }}/releases/${{ inputs.image_tag || github.sha }}

      - name: Push the deployment live
        run: |
          gsutil rsync -r gs://${{ env.GCP_BUCKET }}/releases/${{ inputs.image_tag || github.sha }} gs://${{ env.GCP_BUCKET }}/live

      # - name: Set up terraform
      #   uses: hashicorp/setup-terraform@v3

      # - name: Check version
      #   run: terraform --version

      # - name: Set environment variables
      #   run: |
      #     TERRAFORM_ARGS="-var-file=\"envs/${{ vars.ENV_VAR }}.tfvars\" \
      #       -var=\"image_path=gcr.io/arxiv-development/${{env.IMAGE_NAME}}:${{inputs.image_tag}}\""

      #     echo "TERRAFORM_ARGS=$TERRAFORM_ARGS" >> $GITHUB_ENV
      #   working-directory: terraform/admin-ui

      # - name: Initialize admin-api remote backend
      #   run: terraform init -backend-config="bucket=${{ vars.TERRAFORM_BUCKET }}"
      #   working-directory: terraform/admin-ui

      # - name: Apply
      #   run: terraform apply ${{ env.TERRAFORM_ARGS }} -auto-approve
      #   working-directory: terraform/admin-ui
